name: gallery-img_scraper

on:
  schedule:
    # 특정 시간대마다 실행
    # cron 표현식 - https://crontab.guru/ 참고
    - cron: "30 * * * *"  # 매 시간 30분에 실행
    
  push:
    branches: ["main"]  # 'main' 브랜치에 push 할 때도 실행

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with: 
        TOKEN: ${{ secrets.GA_IMG_SCRAPER_KEY }}

    
    # 파이썬 설치
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    # 파이썬 업그레이드
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    # 라이브러리 설치
    - name: Install Libraries
      run: | 
        pip install requests beautifulsoup4 asyncio aiohttp lxml

    # 파이썬 파일 실행  
    - name: run my file
      run: |
        python3 module/crawler/crawl_saver.py

    # 커밋 & 푸시
    - name: commit & push
      env:
        TOKEN: ${{ secrets.GA_IMG_SCRAPER_KEY }}
      run: |
        git config --global user.email "chiroyawn@gmail.com"
        git config --global user.name "chiroya"
        git add module/crawler/images.json
        git commit -m "Crawing Images Complete" || echo "No changes to commit"
        git push origin main
